version: '3.8'

services:
  # Servicio de la aplicación Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agenda-gerentes-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/agenda_gerentes
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always
    networks:
      - agenda-net
    volumes:
      - ./uploads:/app/uploads

  # Servicio de Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: agenda-gerentes-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=agenda_gerentes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - agenda-net

volumes:
  postgres-data:
    driver: local

networks:
  agenda-net:
    driver: bridge